In [43]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [44]:
folder_path = "/content/drive/MyDrive/data_mining_db"

In [ ]:
import pandas as pd
import os
import unicodedata
import re

In [45]:
total_rows = 0

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder_path, file))
        rows = len(df)
        print(f"{file}: {rows} rows")
        total_rows += rows

print("Total rows in dataset:", total_rows)

Phones.csv: 170 rows
School Bags.csv: 250 rows
Mens Watches.csv: 14 rows
Handbags and Clutches.csv: 250 rows
Home Improvement.csv: 250 rows
T-shirts and Polos.csv: 250 rows
Womens Shoes.csv: 250 rows
Televisions.csv: 250 rows
Womens Watches.csv: 199 rows
Womens Sandals.csv: 250 rows
Motorbike Accessories.csv: 250 rows
Womens Innerwear.csv: 250 rows
Musical Instruments.csv: 250 rows
WomensFashion.csv: 250 rows
Mens Innerwear.csv: 250 rows
Mens Shirts.csv: 250 rows
Cameras.csv: 250 rows
Toys and Games.csv: 250 rows
Mens Formal Shoes.csv: 250 rows
Kids Clothing.csv: 250 rows
Make-up.csv: 250 rows
Headphones.csv: 250 rows
Strength Training.csv: 250 rows
Refrigerators.csv: 250 rows
Mens Sports Shoes.csv: 250 rows
Speakers.csv: 250 rows
Baby Products.csv: 250 rows
WesternWear.csv: 250 rows
Total rows in dataset: 6633

In [46]:
# Combining different CSV files from a data set into one single data frame.
df_list = []

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)

        # Optional: keep track of source file/category
        df["source_file"] = file

        df_list.append(df)

# Combine all into one DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

print("Total rows:", len(combined_df))
combined_df.head()

Total rows: 6633

,name,main_category,image,ratings,no_of_ratings,actual_price,source_file
0,"POCO M3 (Power Black, 6GB RAM, 64GB Storage)",Phones,https://m.media-amazon.com/images/I/819tyWhY0i...,3.9,183.0,12999.0,Phones.csv
1,"iQOO Z6 5G by vivo (Dynamo Black, 4GB RAM, 128...",Phones,https://m.media-amazon.com/images/W/IMAGERENDE...,4.0,22628.0,19990.0,Phones.csv
2,"Samsung Galaxy S22 5G (Phantom White, 8GB RAM,...",Phones,https://m.media-amazon.com/images/I/71HUnJvHsb...,4.3,1369.0,85999.0,Phones.csv
3,Samsung Galaxy Tab A7 Lite 8.7 inches with Cal...,Phones,https://m.media-amazon.com/images/I/91SpB-8UCu...,4.2,5174.0,17500.0,Phones.csv
4,"Samsung Galaxy M53 5G (Deep Ocean Blue, 8GB, 1...",Phones,https://m.media-amazon.com/images/I/81yL2dXKTH...,3.9,9708.0,34999.0,Phones.csv

In [47]:
# Checking for NaN values
combined_df.isnull().sum()

name             0
main_category    0
image            0
ratings          0
no_of_ratings    0
actual_price     0
source_file      0
dtype: int64

In [48]:
# Checking for empty or misiing values
(combined_df == '').sum()

name             0
main_category    0
image            0
ratings          0
no_of_ratings    0
actual_price     0
source_file      0
dtype: int64

In [49]:
# Checking for duplicate values and also dropping them

print("Number of Duplicates present: ",combined_df.duplicated().sum())

combined_df[combined_df.duplicated(keep=False)]

combined_df = combined_df.drop_duplicates(subset=['name', 'main_category', 'actual_price'])

print("Number of Duplicates present after clean up: ",combined_df.duplicated().sum())

Number of Duplicates present:  12
Number of Duplicates present after clean up:  0

In [50]:
combined_df.info()

# Change the dtypr of the column no_of_ratings to int from float
combined_df['no_of_ratings'] = combined_df['no_of_ratings'].astype(int)

# Change the dtypr of the column actual_price to int from float
combined_df['actual_price'] = combined_df['actual_price'].astype(int)

<class 'pandas.core.frame.DataFrame'>
Index: 6579 entries, 0 to 6632
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6579 non-null   object
 1   main_category  6579 non-null   object
 2   image          6579 non-null   object
 3   ratings        6579 non-null   float64
 4   no_of_ratings  6579 non-null   float64
 5   actual_price   6579 non-null   float64
 6   source_file    6579 non-null   object
dtypes: float64(3), object(4)
memory usage: 411.2+ KB

In [52]:
#  Standardizing Text Columns
combined_df['name'] = combined_df['name'].str.strip()

In [53]:
# Checking the categories in main_category
combined_df['main_category'].unique()

array(['Phones', 'School Bags', 'Mens Watches', 'Handbags and Clutches',
       'Home Improvement', 'T-shirts and Polos', 'Womens Shoes',
       'Televisions', 'Womens Watches', 'Womens Sandals',
       'Motorbike Accessories', 'Womens Innerwear', 'Musical Instruments',
       'Womens Fashion', 'Mens Innerwear', 'Mens Shirts', 'Cameras',
       'Toys', 'Mens Formal Shoes', 'Kids Clothing', 'Make-up',
       'Headphones', 'Strength Training', 'Refrigerators',
       'Mens Sports Shoes', 'Speakers', 'Baby Products'], dtype=object)

In [54]:
# Changinf the column name make-up to makeup

combined_df['main_category'] = combined_df['main_category'].replace({
    'make-up': 'makeup',
    't-shirts and polos': 'tshirts and polos',
})

In [55]:
#  Checking if all rating are valid
combined_df[(combined_df['ratings'] < 0) | (combined_df['ratings'] > 5)]

Empty DataFrame
Columns: [name, main_category, image, ratings, no_of_ratings, actual_price, source_file]
Index: []

In [65]:
# #  Checking if the actual_price column has any -ve values
combined_df[combined_df['actual_price'] <= 0]

USD_PER_INR = 0.012  # 1 INR ≈ 0.012 USD (update as needed)

combined_df['actual_price_usd'] = (combined_df['actual_price'] * USD_PER_INR).round(2)

In [68]:
# search corpus

# Reset index and create product_id
combined_df = combined_df.reset_index(drop=True)
combined_df['product_id'] = combined_df.index

# Create searchable text corpus
combined_df['search_text'] = (
    'product: ' + combined_df['name'] + '. ' +
    'category: ' + combined_df['main_category'] + '. ' +
    'price: $' + combined_df['actual_price_usd'].astype(str) + '. ' +
    'rating: ' + combined_df['ratings'].astype(str) + ' out of 5. ' +
    'reviews: ' + combined_df['no_of_ratings'].astype(str) + '. ' +
    combined_df['name']
)

# Clean text for embeddings
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

combined_df['search_text'] = combined_df['search_text'].apply(clean_text)

combined_df.head()

,name,main_category,image,ratings,no_of_ratings,actual_price,source_file,product_id,search_text,actual_price_usd
0,"POCO M3 (Power Black, 6GB RAM, 64GB Storage)",Phones,https://m.media-amazon.com/images/I/819tyWhY0i...,3.9,183,12999,Phones.csv,0,"product: poco m3 (power black, 6gb ram, 64gb s...",155.99
1,"iQOO Z6 5G by vivo (Dynamo Black, 4GB RAM, 128...",Phones,https://m.media-amazon.com/images/W/IMAGERENDE...,4.0,22628,19990,Phones.csv,1,"product: iqoo z6 5g by vivo (dynamo black, 4gb...",239.88
2,"Samsung Galaxy S22 5G (Phantom White, 8GB RAM,...",Phones,https://m.media-amazon.com/images/I/71HUnJvHsb...,4.3,1369,85999,Phones.csv,2,"product: samsung galaxy s22 5g (phantom white,...",1031.99
3,Samsung Galaxy Tab A7 Lite 8.7 inches with Cal...,Phones,https://m.media-amazon.com/images/I/91SpB-8UCu...,4.2,5174,17500,Phones.csv,3,product: samsung galaxy tab a7 lite 8.7 inches...,210.00
4,"Samsung Galaxy M53 5G (Deep Ocean Blue, 8GB, 1...",Phones,https://m.media-amazon.com/images/I/81yL2dXKTH...,3.9,9708,34999,Phones.csv,4,product: samsung galaxy m53 5g (deep ocean blu...,419.99

In [58]:
# Cleaning text to create emdeding

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

combined_df['search_text'] = combined_df['search_text'].apply(clean_text)

combined_df.head()

,name,main_category,image,ratings,no_of_ratings,actual_price,source_file,product_id,search_text
0,"POCO M3 (Power Black, 6GB RAM, 64GB Storage)",Phones,https://m.media-amazon.com/images/I/819tyWhY0i...,3.9,183,12999,Phones.csv,0,"product: poco m3 (power black, 6gb ram, 64gb s..."
1,"iQOO Z6 5G by vivo (Dynamo Black, 4GB RAM, 128...",Phones,https://m.media-amazon.com/images/W/IMAGERENDE...,4.0,22628,19990,Phones.csv,1,"product: iqoo z6 5g by vivo (dynamo black, 4gb..."
2,"Samsung Galaxy S22 5G (Phantom White, 8GB RAM,...",Phones,https://m.media-amazon.com/images/I/71HUnJvHsb...,4.3,1369,85999,Phones.csv,2,"product: samsung galaxy s22 5g (phantom white,..."
3,Samsung Galaxy Tab A7 Lite 8.7 inches with Cal...,Phones,https://m.media-amazon.com/images/I/91SpB-8UCu...,4.2,5174,17500,Phones.csv,3,product: samsung galaxy tab a7 lite 8.7 inches...
4,"Samsung Galaxy M53 5G (Deep Ocean Blue, 8GB, 1...",Phones,https://m.media-amazon.com/images/I/81yL2dXKTH...,3.9,9708,34999,Phones.csv,4,product: samsung galaxy m53 5g (deep ocean blu...

In [59]:
#Remove special characters

combined_df['name'] = combined_df['name'].apply(lambda x: unicodedata.normalize('NFKD', str(x)))

In [60]:
# Checking the content lenght
combined_df['search_text'].str.len().describe()

count    6579.000000
mean      249.984496
std        69.496504
min       104.000000
25%       188.000000
50%       244.000000
75%       331.000000
max       350.000000
Name: search_text, dtype: float64